### ISSUE TITLE
with v20190213 font-size changed break some design 

### ISSUE THREAD

**Issue by pieplu** [NicoHood/arc-theme#197]
Since I have updated for 20190213, I will discovert some design changes, maybe unwanted:

![image](https://user-images.githubusercontent.com/3260285/53116110-d96e9880-3515-11e9-93a7-ffa26970d843.png)

(no more round ...), and all text looks bigger.

I thinks this PR can be the root cause: #171 . Base font-size was 9, and became 10

In more, I will suggest you to use `rem` (insted font-size * some value), with a sass function, like that:

```scss
@function strip-units($val) {
  @return ($val / ($val * 0 + 1));
}

@function rem($pxval) {
  @if not unitless($pxval) {
    $pxval: strip-units($pxval);
  }
  $base: $base-font-size;
  @if not unitless($base) {
    $base: strip-units($base);
  }
  @return ($pxval / $base) * 1rem;
}

// ---

.somSelector {
  font-size: rem(14);
}
```

### Details

- Distribution (with version): Arch Linux Latest
- Desktop environment (with version): Gnome 3.30
- Arc version/commit (don't put "latest"):  20190213
- GTK+ 3 version:
  - Murrine engine version:
  - `gnome-themes-extras` version:
- Installation method (package or source): AUR package
